services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:v0.6.14
    container_name: adguardhome-sync
    restart: unless-stopped
    network_mode: host
    environment:
      - CONFIG_FILE=/config/adguardhome-sync.yaml
    volumes:
      - ./adguardhome-sync.yaml:/config/adguardhome-sync.yaml:ro
