server:
    verbosity: 1
    interface: 127.0.0.1@5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes
    do-ip6: no                       # Tắt triệt để IPv6 theo chuẩn Pure IPv4 của homelab

    # Kiểm soát truy cập nội bộ
    access-control: 127.0.0.0/8 allow

    # Tối ưu bảo mật và Privacy
    hide-identity: yes
    hide-version: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: no
    edns-buffer-size: 1232
    prefetch: yes
    prefetch-key: yes
    num-threads: 1

    # Tối ưu kích thước Cache (RAM ~128MB)
    msg-cache-size: 32m
    rrset-cache-size: 64m
    infra-cache-numhosts: 10000
